# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-16 10:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 16, 19, 24, 47, 354656)),
        ),
    ]
