# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 04:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_auto_20170716_1924'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 13, 52, 35, 334819)),
        ),
    ]
