# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-17 06:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_auto_20170717_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=255)),
                ('create_date', models.DateTimeField(default=datetime.datetime(2017, 7, 17, 15, 17, 55, 912202))),
            ],
        ),
        migrations.AlterField(
            model_name='boards',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 17, 15, 17, 55, 911703)),
        ),
        migrations.AddField(
            model_name='comment',
            name='board_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Boards'),
        ),
    ]
