# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 02:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20170717_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boards',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 11, 23, 25, 739225)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='board_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='board_id', to='board.Boards'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 11, 23, 25, 739725)),
        ),
    ]
