# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-18 03:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20170718_1123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='board_id',
            new_name='board',
        ),
        migrations.AlterField(
            model_name='boards',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 12, 15, 15, 827169)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='create_date',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 18, 12, 15, 15, 828170)),
        ),
    ]
